version: "3"

services:

  bt-server-dev:
    env_file:
      - .env
    container_name: bt-server-dev
    restart: on-failure:3
    image: ${BT_IMAGE_NAME}
    build:
      context: ./bt
      dockerfile: Dockerfile
    ports:
      - "${PORT_CUSTOM}"
      - "${PORT_FTP}"
      - "${PORT_8888}:8888"
      - "${PORT_8080}:8080"
      - "${PORT_888}:888"
      - "${PORT_443}:443"
      - "${PORT_80}:80"
      - "${PORT_21}:21"
      - "${PORT_20}:20"
